# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 668)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(42, 88, 761, 551))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.graphicsView.setMaximumSize(QtCore.QSize(701, 16777215))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.layoutWidget)
        self.horizontalScrollBar.setMaximumSize(QtCore.QSize(691, 16777215))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.verticalLayout.addWidget(self.horizontalScrollBar)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 30, 527, 40))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setMaximumSize(QtCore.QSize(77, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.line = QtWidgets.QFrame(self.layoutWidget1)
        self.line.setMaximumSize(QtCore.QSize(3, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setMaximumSize(QtCore.QSize(76, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_5.setMaximumSize(QtCore.QSize(3, 16777215))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout.addWidget(self.line_5)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setMaximumSize(QtCore.QSize(77, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_6.setMaximumSize(QtCore.QSize(3, 16777215))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_4.setMaximumSize(QtCore.QSize(76, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_2.setMaximumSize(QtCore.QSize(3, 16777215))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_5.setMaximumSize(QtCore.QSize(77, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_4.setMaximumSize(QtCore.QSize(3, 16777215))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_6.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(821, 71, 171, 561))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_23 = QtWidgets.QPushButton(self.widget)
        self.pushButton_23.setMaximumSize(QtCore.QSize(191, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_2.addWidget(self.pushButton_23)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.buttonGroup1 = QtWidgets.QButtonGroup(self.widget)
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.buttonGroup1.addButton(self.radioButton)
        self.radioButton.setMaximumSize(QtCore.QSize(101, 16777215))
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.buttonGroup1.addButton(self.radioButton_2)
        self.radioButton_2.setMaximumSize(QtCore.QSize(101, 16777215))
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
        self.buttonGroup1.addButton(self.radioButton_3)
        self.radioButton_3.setMaximumSize(QtCore.QSize(101, 16777215))
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonGroup2 = QtWidgets.QButtonGroup(self.widget)
        self.radioButton_6 = QtWidgets.QRadioButton(self.widget)
        self.buttonGroup2.addButton(self.radioButton_6)
        self.radioButton_6.setMaximumSize(QtCore.QSize(101, 16777215))
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_2.addWidget(self.radioButton_6, 0, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.widget)
        self.buttonGroup2.addButton(self.radioButton_5)
        self.radioButton_5.setMaximumSize(QtCore.QSize(101, 16777215))
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_2.addWidget(self.radioButton_5, 1, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget)
        self.buttonGroup2.addButton(self.radioButton_4)
        self.radioButton_4.setMaximumSize(QtCore.QSize(101, 16777215))
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_2.addWidget(self.radioButton_4, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setMaximumSize(QtCore.QSize(87, 16777215))
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setMaximumSize(QtCore.QSize(86, 16777215))
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_3.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setMaximumSize(QtCore.QSize(87, 16777215))
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_3.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_4.setMaximumSize(QtCore.QSize(86, 16777215))
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_3.addWidget(self.checkBox_4, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_11 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_11.setMaximumSize(QtCore.QSize(124, 16777215))
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_4.addWidget(self.checkBox_11, 0, 0, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_12.setMaximumSize(QtCore.QSize(124, 16777215))
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_4.addWidget(self.checkBox_12, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.actionopen.setFont(font)
        self.actionopen.setObjectName("actionopen")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "姿态"))
        self.pushButton_2.setText(_translate("MainWindow", "关节"))
        self.pushButton_3.setText(_translate("MainWindow", "算法"))
        self.pushButton_4.setText(_translate("MainWindow", "性能"))
        self.pushButton_5.setText(_translate("MainWindow", "温度"))
        self.pushButton_6.setText(_translate("MainWindow", "状态"))
        self.pushButton_23.setText(_translate("MainWindow", "打开"))
        self.radioButton.setText(_translate("MainWindow", "Angle"))
        self.radioButton_2.setText(_translate("MainWindow", "velocity"))
        self.radioButton_3.setText(_translate("MainWindow", "Torque"))
        self.radioButton_6.setText(_translate("MainWindow", "HipX"))
        self.radioButton_5.setText(_translate("MainWindow", "HipY"))
        self.radioButton_4.setText(_translate("MainWindow", "Knee"))
        self.checkBox.setText(_translate("MainWindow", "FL"))
        self.checkBox_2.setText(_translate("MainWindow", "FR"))
        self.checkBox_3.setText(_translate("MainWindow", "HL"))
        self.checkBox_4.setText(_translate("MainWindow", "HR"))
        self.checkBox_11.setText(_translate("MainWindow", "command"))
        self.checkBox_12.setText(_translate("MainWindow", "actual"))
        self.actionopen.setText(_translate("MainWindow", "open"))
